{% set name = "litereval" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2df538916be7aca13c2ebe6afa98ce7b0bbd683b28425189bfa1f24582f512d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - litereval

about:
  home: https://github.com/kiwi0fruit/litereval
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Wrapper around ast.literal_eval with new {foo='bar', key=None} dict syntax."
  doc_url: https://github.com/kiwi0fruit/litereval
  dev_url: https://github.com/kiwi0fruit/litereval

extra:
  recipe-maintainers:
    - kiwi0fruit
