travis:
  secure:
    BINSTAR_TOKEN: deXUdTKwL0uRX4ktNIKG8HGLwrkDsTeqtyF0BTQ3RybwdWzFL1kBxwIFJQ7yfa1loSCOurwXneNTlyuq6VsWPaUaAg6jKEYxxu5Lzn1Pdi4vkKyrdP8KKnmokPzjOOUAqhk4R9FUDX02DS62/YQDk9SaToM6CDn4Mo2e682MqGGr8U13Ma2vw3EpmJZ9tpaS2BLRhFbVXc1AAlm2LiufeH+utoLhgqTyYQ6qXKoOjrW8Y45CGSfyQvJ7G49kiW3thYqazJhwdXPNGCkxQHPICmDtubJldOGxjR2G5Rxxvd0UuAn+Rg/yi4Akwmc98he7YkhPHl34qNlYyiK0KR8OQPR11MtEM1qKjyVhQnpBc/7l7s3hSGkkxdNeDOsHnPoWE9iKSnmarrpcjcVip03cXb/GLFclsXzIScJbK4jnArMkqrgFL7yrFK7YyujVLAEeRHiPRE3LHowSKiou2IdrfXCveAe5oIHiimoDUzZDPfv426Qz9KnyeG2tqCTbPSfLvBLJVzfLOuSB/CCQRIx7oT4HNG2pSB/aAbaqSJkh5B3wSIDpZ0mEkHhnZbVhBk/zamsamX+Eik/ZLMv45KeP876cgKvH7nTs2hExNoyRxBoRsbTioS7pOaCu8ejDIKAH9+33dQes1drmYOlb+ygOBOLVc47WVtSNXZHIChkMkPk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
